interm(0,zero).
interm(1,one).
interm(2,two).
interm(3,three).
interm(4,four).
interm(5,five).
interm(6,six).
interm(7,seven).
interm(8,eight).
interm(9,nine).
to_words([X],[Y]):-interm(X,Y).
to_words([X|X1],[Y|Y1]):-interm(X,Y),to_words(X1,Y1).
